server:
  port: 8085

spring:

  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/socialpractice
    username: sa
    password:


  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


  # Spring Security OAuth
  security:
    oauth2:
      client:
        registration:
          # Client Information in each social
          naver:
            clientId: cVd6X2C5bqpgU7kx0GgH
            clientSecret: DSejIKOqEH
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8085/login/oauth2/code/naver
            scope: profile, email

          google:
            clientId: 61872103088-jbu3mh1g28iqj5oh3mkq50g1qhen4h2p.apps.googleusercontent.com
            clientSecret: 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
            scope: profile,email
            redirectUri: http://localhost:8085/login/oauth2/code/google

          kakao:
            clientId: 8906f358e90b2bb031670818ce9a56c4
            clientSecret: pfoR97dsi5xYuuhS7HVWfgNLVzvG93Mx
            authorizationGrantType: authorization_code
            clientName: client-app
            redirectUri: http://localhost:8085/login/oauth2/code/kakao
            clientAuthenticationMethod: post
            scope: profile_nickname,profile_image,account_email,openid

          github:
            clientId: ce1863e79f6df3e49278
            clientSecret: a70b2cc6e7c5658e16ab55466ac3fadc501a1b1c
            scope: user
            redirectUri: http://localhost:8085/login/oauth2/code/github

          facebook:
            clientId: 590463959149868
            clientSecret: 9172abf66cac532c72c6dc5d69bc4144
            scope: email, public_profile
            redirectUri: http://localhost:8085/login/oauth2/code/facebook


        # social provider
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            issuerUri: https://kauth.kakao.com
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
#            userInfoUri: https://kapi.kakao.com/v2/user/me
            userInfoUri: https://kapi/kakao.com/v1/oidc/userinfo
            jwkSetUri: https://kauth.kakao.com/.well-known/jwks.json
            userNameAttribute: id




  mvc:
    static-path-pattern: /static/**

logging:
  level:
    org.hibernate.SQL: debug

